//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPallete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int ThemeID { get; set; }
        public string ThemeName { get; set; }
        public string ThemeCSS { get; set; }
    }
}
